add_newline = true

[aws]
disabled = true

[env_var.GEPPETTO_ENV]
variable = "GEPPETTO_ENV"
format = "[gcli: ($env_value) ]($style)"
default = ""
style = "bold yellow"

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vicmd_symbol = "[â®](bold yellow)"

[directory]
read_only = "ğŸ”’"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "ï˜ "

# [git_status]
# style = "fg:yellow"
# ahead = "â‡¡${count}"
# behind = "â‡£${count}"
# diverged = "â‡•${count}"
# staged = "[â—](green) "
# untracked = "[â€¦](red) "
# modified = "[Â±](yellow) "

[golang]
symbol = "go "

[docker_context]
symbol = "ïŒˆ "
style = "bold fg:blue"
